import React from "react";
import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body>
        <AppRouterCacheProvider>
            {children}
            <Box>
                csakncknsa
            </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
